### ISSUE TITLE
Error with Date value

### ISSUE THREAD

**Issue by AlvaroSevilla** [RaymarMonte/apex-create-xlsx#2]
Hi Raymar.
Thank you for your great contribution, i am using to develop an big excel document, but in this moment i am having a issue to set a date value "01/05/2021", i'm receiving an error 
FATAL_ERROR System.JSONException: Invalid format: ""13/04/2021"" at [line:1, column:133]
FATAL_ERROR System.VisualforceException: Invalid format: ""13/04/2021"" at [line:1, column:133]

it just works with "Sun Oct   30 00:00:00 GMT 2016" and the excel document convert my value in this format always
Can you give me some idea to fix that issue?

**Comment by RaymarMonte** [comment]
Hi there. Apologies for not being able to reply sooner. Were you able to resolve your issue?

**Comment by AlvaroSevilla** [comment]
Hi, Yes i was able to solve the issue, it was actually mistake my myself.

**Comment by AlvaroSevilla** [comment]
Hi, it's me again, I had to forget the idea to create a excel file, because i had a lot of issue for the row's quantity,  last errors were:
Collection size 1,768 exceeds maximum size of 1,000.
Apex CPU Time Limit execeeded
And I need to create an excel file from apex batch process.
If you have some ide i would like hear it.

**Comment by RaymarMonte** [comment]
Looks like an Apex error this time. I tried researching your issue and found this: https://salesforce.stackexchange.com/questions/221782/collection-size-1-768-exceeds-maximum-size-of-1-000

Have you seen this one yet?
